{% set name = "aiogram" %}
{% set version = "2.20" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v2.20
  git_url: https://github.com/aiogram/aiogram.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - aiohttp
    - Babel
    - certifi

test:
  imports:
    - aiogram

about:
  home: https://aiogram.dev/
  license: MIT License
  license_family: MIT
  summary: Modern and fully asynchronous framework for Telegram Bot API 
